---
title: "compute Rt benchmark"
author: "Joaquin Salas"
date: "17/1/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width=3, fig.height=2)
```

## Introduction

A direct method to compute $R_t$, the effective reproduction number.
This contains the exact solution to the linear problem. 

Here, we compare our approach with Cori et al. using a synthetic sequence created with a SERI model.

```{r }


library(magrittr) # %>%
library(ggplot2)
library(reshape2)

library(matrixStats) #colSds
library(latex2exp) #latex expression in figure labels
library(EpiEstim) #estimate R


#instructions from <02-make_fig_compare_estimators> some of the instructions are duplicated
suppressMessages(library(dplyr))
suppressMessages(library(tidyr))
library(readr)
library(cowplot)



code.dir = 'E:/Documents/informs/research/2021.01.14 Rt/code/'
setwd(code.dir)
data.dir = 'E:/Documents/informs/research/2021.01.14 Rt/data/'


filename = paste(code.dir, "Rt_estimation/analyses/true_pars.rds", sep = "")
parlist <- read_rds(filename)

#include code
filename = paste(code.dir, "Rt_estimation/code/util.R", sep = "")
source(filename)

filename = paste(code.dir, "simpleRt.R", sep = "")
source(filename)


data = get_sim_df() %>% filter(time < 150)



#display the synthetic sequence
infected = data.frame(date= data$time, t = data$time, I = data$incidence)

p = ggplot(data = infected)+
  geom_line(aes(x = date, y = I, group = 1), size=2, color = "blue" )+
  theme(axis.text= element_text(size = 14)) +
  theme(axis.title= element_text(size = 14)) +
  ylab("infected")+
  theme (legend.position = "none",
         axis.text.x = element_text(angle = 0, hjust = 1))
                                                     

suppressMessages(suppressWarnings(print(p)))
suppressMessages(suppressWarnings(ggsave("../figures/synthetic_seq.png")))





# Compute Rt

#generative period
T = 13 #indices running from 0, 1, 2, 3,.. T

gen.period <- NULL 
Rt <- NULL

for (init in seq(1,dim(infected)[1]-T-1)) {
  Ip = infected$I[init:(init+T)]
  
  A = fillMatrix(Ip, T)

  res <- generative (A, T)
  
  pred = 1/res$x[T+1] * (Ip[seq(T,1,-1)] %*% res$x[1:T])
  rec = data.frame(date = infected$date[init+T], 
                   t = init+T-1, 
                   v = res$x[T+1], 
                   error = res$error, 
                   I.Tp1 = Ip[T+1], pred = pred)
  
  Rt = rbind(Rt, rec)
  
  gen.period <-rbind(gen.period, res$x[1:T])

}



p <- suppressMessages(suppressWarnings(ggplot(Rt,aes(x = error)) +
  geom_histogram( fill = "red", color = "black", bin = 30)+
  theme(axis.text= element_text(size = 8)) +
  theme(axis.title= element_text(size = 8)) +
  xlab("optimization error")))
suppressMessages(suppressWarnings(print(p)))
suppressMessages(suppressWarnings(ggsave("../figures/histOptError.png") )) 


p <- suppressMessages(suppressWarnings(ggplot(Rt,aes(x = I.Tp1 - pred)) +
  geom_histogram( fill = "red", color = "black", bin = 30)+
  theme(axis.text= element_text(size = 8)) +
  theme(axis.title= element_text(size = 8)) +
  xlab("fit error")))
suppressMessages(suppressWarnings(print(p)))
suppressMessages(suppressWarnings(ggsave("../figures/histFitError.png") )) 
  
  

#draw w

filename = paste(data.dir, "Rt_SEIR.csv", sep = "")
write.csv(Rt, filename)



#################################
#visualize the generative period
################################
grid = matrix(0, nrow=dim(gen.period)[1], ncol = dim(gen.period)[2])
num.rep = dim(gen.period)[2]
for (y in seq(1, dim(gen.period)[1])) {
  grid[y,] = seq(1,dim(gen.period)[2])
  
}



x = as.vector(grid)
y = as.vector(gen.period)

w.pdf = data.frame(x=as.factor(x), y=y)


standard.deviation = colSds(gen.period)
media = colMeans(gen.period)

gen.period.stat = data.frame (x = seq(1, T), mu = media, sd = standard.deviation)



p = suppressMessages(suppressWarnings(ggplot(data = gen.period.stat) +
  geom_line(aes(x = x, y = media),size=1, color = "green")+
  
  geom_ribbon(aes(x=x,y=mu, ymin=mu-sd, ymax=mu+sd),
              linetype=2, alpha=0.2, color="green")+
  
  xlab(TeX("$w$"))+
  ylab(TeX("$p(w)$"))))
  
suppressMessages(suppressWarnings(print(p)))





p <- suppressMessages(suppressWarnings(ggplot(w.pdf, aes(x,y)) + stat_bin2d()+
  geom_bin2d(binwidth = c(1, 0.01)) +
#  scale_fill_gradient2(low="green", high = "darkgreen")  +
  theme (#legend.position = "none",
         axis.text.x = element_text(angle = 0, hjust = 1))+
  geom_line(data = gen.period.stat, aes(x = x, y = mu),size=1, color = "red") +
  xlab(TeX("w"))+
  ylab(TeX("p(w)"))+  
  theme(axis.text= element_text(size = 8)) +
  theme(axis.title= element_text(size = 8)))) 
suppressMessages(suppressWarnings(print(p)))

suppressMessages(suppressWarnings(ggsave("../figures/w-pdf-syn.png")))

p<- p+ylim(0,0.15) + theme (legend.position = "none",
         axis.text.x = element_text(angle = 0, hjust = 1))
suppressMessages(suppressWarnings(print(p)))
suppressMessages(suppressWarnings(ggsave("../figures/w-pdf-detail-syn.png")))





standard.deviation = colSds(gen.period)
media = colMeans(gen.period)

gen.period.stat = data.frame (x = seq(1, T), mu = media, sd = standard.deviation)

p = ggplot(data = gen.period.stat) +
  geom_line(aes(x = x, y = media),size=1, color = "blue")+
  geom_ribbon(aes(x=x,y=mu, ymin=mu-sd, ymax=mu+sd),
              linetype=2, alpha=0.2, fill= "blue")+
  theme(axis.text= element_text(size = 14)) +
  theme(axis.title= element_text(size = 14)) +
  xlab(TeX("$w$"))+
  ylab(TeX("$p(w)$"))
suppressMessages(suppressWarnings(print(p)))

suppressMessages(suppressWarnings(ggsave("../figures/w_synthetic.png")))




#read cori result from Rt_estimation program stores in cori_wt_fits_rt.rds
filename = paste(code.dir, "Rt_estimation/analyses/cori_wt_fits_rt.rds", sep = "")
cori_wt = readRDS(filename)
init = which(cori_wt$time == Rt$t[1])
terminate = which(cori_wt$time == Rt$t[dim(Rt)[1]])
cori_wt = cori_wt[init:terminate,]


RtNow = data.frame(days = cori_wt$time, 
                   R =  cori_wt$Cori.mean,
                       lower =  cori_wt$Cori.025,
                     upper = cori_wt$Cori.975)




RtJoint = cbind(Rt, cori.R = RtNow$R, 
                lower = RtNow$lower, 
                upper = RtNow$upper, 
                true_rt = data$true_rt[(T+1):(dim(data)[1]-1)]  )


p = ggplot(data = RtJoint) +
  geom_line(aes(x = date, y = 1/v, group = 1), color = "blue")+

  geom_line(aes(x = date, y = true_rt, group=1), color = "red")+
  
  geom_line(aes(x = date, y = cori.R, group=1), color = "green")+

   geom_ribbon(data = RtJoint, aes(x=date,y=cori.R,ymin=lower, ymax=upper, group = 1),
                                      linetype=2, alpha=0.1, fill = "green")+
  
  geom_hline(yintercept = 1,
             linetype = "solid", 
             color = "blue", size=0.6) +
  xlab("time") + 
  ylab("Rt")+
  theme (legend.position = "none",
         axis.text.x = element_text(angle = 20, hjust = 1))+
    theme(axis.text= element_text(size = 8)) +
  theme(axis.title= element_text(size = 8)) +
  ylim(0.65,2.5)

suppressMessages(suppressWarnings(print(p)))






filename = paste("../figures/Rt-13.png", sep = "")
suppressMessages(suppressWarnings(ggsave(filename)))



```





